import './globals.css'
import Provider from "@/components/provider";
import ThemeButton from '@/components/themeButton';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeButton />
        <Provider>
          { children }
        </Provider>
      </body>
    </html>
  )
}
